### ISSUE TITLE
Add coach form crashes if no data provided

### ISSUE THREAD

**Issue by isaacmond** [richcooper95/crisis#23]
The add tool errors if no name is provided. 

![image](https://user-images.githubusercontent.com/47224368/99798580-289d8f00-2b29-11eb-9c45-5dbed1c98c67.png)

**Comment by jacriley** [comment]
I imagine this is my bug - will take a look at some point :)

**Comment by jacksonriley** [comment]
Nice easy fix, thanks for finding that Isaac :)
